export const LABEL_MAP: { [key: string]: string } = {
  // Languages
  'python': 'Python',
  'java': 'Java',
  'c#': 'C#',
  'c++': 'C++',
  'php': 'PHP',
  'ruby': 'Ruby',
  'swift': 'Swift',
  'sql': 'SQL',
  'r': 'R',
  'perl': 'Perl',
  'go': 'Go',
  'scala': 'Scala',
  'rust': 'Rust',
  'haskell': 'Haskell',
  'matlab': 'MATLAB',
  'kotlin': 'Kotlin',
  'javascript': 'JavaScript',
  'typescript': 'TypeScript',

  // Frameworks Frontend
  'angular': 'Angular',
  'reactjs': 'ReactJS',
  'svelte': 'Svelte',
  'vue.js': 'Vue.js',
  'jquery': 'jQuery',
  'twitter-bootstrap': 'Bootstrap',
  'tailwind-css': 'Tailwind CSS',
  'flutter': 'Flutter',
  'next.js': 'Next.js',
  'angularjs': 'AngularJS',

  // Frameworks Backend
  'node.js': 'Node.js',
  'django': 'Django',
  'spring': 'Spring',
  'asp.net': 'ASP.NET',
  'laravel': 'Laravel',
  'ruby-on-rails': 'Ruby on Rails',
  'express': 'Express',
  'flask': 'Flask',
  'symfony': 'Symfony',
  'spring-boot': 'Spring Boot',
  '.net-core': '.NET Core',
  'fastapi': 'FastAPI',

  // Mobile Development
  'android': 'Android',
  'ios': 'iOS',
  'react-native': 'React Native',
  'android-studio': 'Android Studio',
  'android-jetpack-compose': 'Android Jetpack Compose',
  'ipad': 'iPad',
  'android-layout': 'Android Layout',
  'xamarin.forms': 'Xamarin.Forms',
  'android-recyclerview': 'Android RecyclerView',
  'android-fragments': 'Android Fragments',
  'iphone': 'iPhone',
  'android-jetpack': 'Android Jetpack',
  'swiftui': 'SwiftUI',
  'android-ndk': 'Android NDK',

  // Database and Data Management
  'mysql': 'MySQL',
  'postgresql': 'PostgreSQL',
  'mongodb': 'MongoDB',
  'sqlite': 'SQLite',
  'sql-server': 'SQL Server',
  'oracle': 'Oracle',
  'firebase': 'Firebase',
  'cassandra': 'Cassandra',
  'redis': 'Redis',
  'dynamodb': 'DynamoDB',
  'neo4j': 'Neo4j',
  'elasticsearch': 'Elasticsearch',
  'dataframe': 'Dataframe',
  'database': 'Database',
  'sqlalchemy': 'SQLAlchemy',
  'mongoose': 'Mongoose',
  'mongodb-query': 'MongoDB Query',
  'database-design': 'Database Design',
  'entity-framework': 'Entity Framework',
  'jpa': 'JPA',
  'hibernate': 'Hibernate',
  'orm': 'ORM',

  // Cloud and DevOps
  'amazon-web-services': 'AWS',
  'azure': 'Azure',
  'google-cloud-platform': 'Google Cloud Platform',
  'docker': 'Docker',
  'kubernetes': 'Kubernetes',
  'jenkins': 'Jenkins',
  'git': 'Git',
  'gitlab': 'GitLab',
  'github': 'GitHub',
  'ansible': 'Ansible',
  'aws-lambda': 'AWS Lambda',
  'azure-devops': 'Azure DevOps',
  'ci/cd': 'CI/CD',
  'aws-cloudformation': 'AWS CloudFormation',
  'terraform': 'Terraform',
  'azure-active-directory': 'Azure Active Directory',
  'kubernetes-helm': 'Kubernetes Helm',
  'amazon-s3': 'Amazon S3',
  'amazon-ec2': 'Amazon EC2',
  'google-kubernetes-engine': 'Google Kubernetes Engine',
  'docker-compose': 'Docker Compose',
  'jenkins-pipeline': 'Jenkins Pipeline',

  // Testing and Automation
  'selenium': 'Selenium',
  'junit': 'JUnit',
  'pytest': 'PyTest',
  'mocha.js': 'Mocha.js',
  'jestjs': 'JestJS',
  'nunit': 'NUnit',
  'testng': 'TestNG',
  'cypress': 'Cypress',
  'automation': 'Automation',
  'unit-testing': 'Unit Testing',
  'end-to-end-testing': 'End-to-End Testing',
  'mocking': 'Mocking',
  'integration-testing': 'Integration Testing',

  // Version Control and Collaboration
  'bitbucket': 'Bitbucket',
  'mercurial': 'Mercurial',
  'svn': 'SVN',
  'github-actions': 'GitHub Actions',
  'gitlab-ci': 'GitLab CI',
  'github-pages': 'GitHub Pages',

  // Operating Systems and Platforms
  'linux': 'Linux',
  'windows': 'Windows',
  'macos': 'MacOS',
  'ubuntu': 'Ubuntu',
  'centos': 'CentOS',
  'wsl': 'WSL',
  'unix': 'Unix',
  'raspberry-pi': 'Raspberry Pi',
  'embedded-linux': 'Embedded Linux',

  // Tools and IDEs
  'visual-studio': 'Visual Studio',
  'visual-studio-code': 'Visual Studio Code',
  'eclipse': 'Eclipse',
  'intellij-idea': 'IntelliJ IDEA',
  'pycharm': 'PyCharm',
  'xcode': 'Xcode',
  'netbeans': 'NetBeans',
  'sublime-text': 'Sublime Text',
  'webstorm': 'WebStorm',
  'vs-code-extensions': 'VS Code Extensions',
  'ide': 'IDE',
  'jetbrains': 'JetBrains',
};
