name: End-to-end tests
on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Specifies the operating system for the job to run on
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Checks out the repository code to the GitHub Actions runner

      # Install dependencies
      - name: Install dependencies
        run: npm install --force  # Installs project dependencies using npm

      # Start the application server using the dev script
      - name: Start application server
        run: npm run start &  # Runs the application server in the background
        env:
          CI: true  # Sets the CI environment variable to true, optimizing Cypress for CI environments

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5  # Runs Cypress end-to-end tests using the official GitHub Action

      # Upload screenshots (if any)
      - uses: actions/upload-artifact@v3
        if: failure()  # Uploads screenshots only if the tests fail
        with:
          name: cypress-screenshots  # Name of the artifact to upload
          path: cypress/screenshots  # Directory path for screenshots

      # Upload videos (always)
      - uses: actions/upload-artifact@v3
        if: failure()  # Always uploads the videos, whether tests pass or fail
        with:
          name: cypress-videos  # Name of the artifact to upload
          path: cypress/videos  # Directory path for videos
