name: End-to-end tests
on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm ci --force

      # Start the application server using the dev script
      - name: Start application server
        run: npm run start &
        env:
          CI: true

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5

      # Upload screenshots (if any)
      - uses: actions/upload-artifact@v3
        if: failure()  # Uploads screenshots only if the tests fail
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload videos (always)
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
